# Generated by Django 6.0.8 on 2026-09-30 09:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_checkout_atencion_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='imagen_archivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen subida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_archivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen subida'),
        ),
    ]
