# Generated by Django 6.0.8 on 2026-10-02 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_combo_imagen_archivo_producto_imagen_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('revisar_stock', 'Revisar stock'), ('revision_pago', 'Revisar pago'), ('reembolsado', 'Reembolsado')], db_index=True, default='pendiente', max_length=16),
        ),
    ]
