# Generated by Django 6.0.8 on 2026-10-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_itempedido_producto_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='checkout_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='checkout_payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preferencia_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
