# Generated by Django 6.0.8 on 2026-10-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_seed_sabor_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagos_adicionales',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
