# Generated by Django 6.0.8 on 2026-10-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_pedido_pagos_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('revisar_stock', 'Revisar stock'), ('revision_pago', 'Revisar pago'), ('reembolsado', 'Reembolsado'), ('contracargo', 'Contracargo')], db_index=True, default='pendiente', max_length=16),
        ),
    ]
